name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - uses: NuGet/setup-nuget@v2
    - run: nuget restore FirefoxAction.csproj
    - run: msbuild FirefoxAction.csproj -t:rebuild -property:Configuration=Release
    - uses: actions/upload-artifact@v4
      with:
        name: dll
        path: ./bin/Release/net40/FirefoxAction.CA.dll